spring:
  datasource:
    url: jdbc:mysql://localhost:3306/etc_system?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: WJHsr021206
    driver-class-name: com.mysql.cj.jdbc.Driver